mtprotosender.py:228 #INFO     [2025-10-02 14:27:23,963] - telethon.network.mtprotosender - 0| Connecting to 149.154.167.51:443/TcpFull...
mtprotosender.py:279 #INFO     [2025-10-02 14:27:24,052] - telethon.network.mtprotosender - 0| Connection to 149.154.167.51:443/TcpFull complete!
handlers.py:17 #INFO     [2025-10-02 14:27:27,379] - root - 0| Handler called. NewMessage. type = <class 'telethon.tl.patched.Message'>
api_interface.py:150 #INFO     [2025-10-02 14:27:29,051] - venv - 0| 200 | https://tenerife.chat/chat/webhook/telegram/create | {'success': True, 'method': 'create'}
handlers.py:17 #INFO     [2025-10-02 14:27:34,215] - root - 0| Handler called. NewMessage. type = <class 'telethon.tl.patched.Message'>
api_interface.py:150 #INFO     [2025-10-02 14:27:34,446] - venv - 0| 200 | https://tenerife.chat/chat/webhook/telegram/create | {'success': True, 'method': 'create'}
handlers.py:17 #INFO     [2025-10-02 14:27:38,851] - root - 0| Handler called. NewMessage. type = <class 'telethon.tl.patched.Message'>
handlers.py:17 #INFO     [2025-10-02 14:27:38,856] - root - 0| Handler called. NewMessage. type = <class 'telethon.tl.patched.Message'>
api_interface.py:150 #INFO     [2025-10-02 14:27:39,090] - venv - 0| 200 | https://tenerife.chat/chat/webhook/telegram/create | {'success': True, 'method': 'create'}
api_interface.py:150 #INFO     [2025-10-02 14:27:39,232] - venv - 0| 200 | https://tenerife.chat/chat/webhook/telegram/create | {'success': True, 'method': 'create'}
mtprotosender.py:319 #INFO     [2025-10-02 14:27:41,329] - telethon.network.mtprotosender - 0| Disconnecting from 149.154.167.51:443/TcpFull...
mtprotosender.py:339 #INFO     [2025-10-02 14:27:41,329] - telethon.network.mtprotosender - 0| Disconnection from 149.154.167.51:443/TcpFull complete!
base_events.py:1758 #ERROR    [2025-10-02 14:27:41,405] - asyncio - 0| Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001440D872350>
base_events.py:1758 #ERROR    [2025-10-02 14:27:41,405] - asyncio - 0| Unclosed connector
connections: ['deque([(<aiohttp.client_proto.ResponseHandler object at 0x000001440D8899C0>, 1216011.75)])']
connector: <aiohttp.connector.TCPConnector object at 0x000001440D872410>
base_events.py:1758 #ERROR    [2025-10-02 14:27:41,405] - asyncio - 0| Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x000001440D983100>
transport: <_ProactorSocketTransport fd=1052 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "C:\Users\Valentyn\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 690, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Users\Valentyn\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 365, in write
    self._loop_writing(data=bytes(data))
  File "C:\Users\Valentyn\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 401, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
