mtprotosender.py:228 #INFO     [2025-10-03 19:55:28,497] - telethon.network.mtprotosender - 0| Connecting to 149.154.167.51:443/TcpFull...
mtprotosender.py:279 #INFO     [2025-10-03 19:55:28,537] - telethon.network.mtprotosender - 0| Connection to 149.154.167.51:443/TcpFull complete!
updates.py:443 #INFO     [2025-10-03 19:55:46,917] - telethon.client.updates - 0| Got difference for channel 3139065215 updates
handlers.py:115 #INFO     [2025-10-03 19:55:46,917] - root - 0| Handler called. ChatAction
handlers.py:115 #INFO     [2025-10-03 19:55:46,917] - root - 0| Handler called. ChatAction
updates.py:590 #ERROR    [2025-10-03 19:55:47,350] - telethon.client.updates - 0| Unhandled exception on event_chat_action
Traceback (most recent call last):
  File "C:\Users\Valentyn\PycharmProjects\tgbot-microservice\.venv\lib\site-packages\telethon\client\updates.py", line 574, in _dispatch_update
    await callback(event)
  File "C:\Users\Valentyn\PycharmProjects\tgbot-microservice\app\handlers.py", line 131, in event_chat_action
    full = await Config.TG_CLIENT(GetFullChatRequest(act_msg.peer_id.chat_id))
AttributeError: 'PeerChannel' object has no attribute 'chat_id'
updates.py:344 #INFO     [2025-10-03 19:56:28,457] - telethon.client.updates - 0| Got difference for account updates
handlers.py:115 #INFO     [2025-10-03 19:56:28,457] - root - 0| Handler called. ChatAction
updates.py:443 #INFO     [2025-10-03 19:56:28,519] - telethon.client.updates - 0| Got difference for channel 1680980716 updates
updates.py:590 #ERROR    [2025-10-03 19:56:28,552] - telethon.client.updates - 0| Unhandled exception on event_chat_action
Traceback (most recent call last):
  File "C:\Users\Valentyn\PycharmProjects\tgbot-microservice\.venv\lib\site-packages\telethon\client\updates.py", line 574, in _dispatch_update
    await callback(event)
  File "C:\Users\Valentyn\PycharmProjects\tgbot-microservice\app\handlers.py", line 122, in event_chat_action
    chat_id, chat_info = await ChatInfo.obj_from_peer(act_msg.peer_id)
  File "C:\Users\Valentyn\PycharmProjects\tgbot-microservice\app\api_interface.py", line 61, in obj_from_peer
    username=chat_obj.username,
AttributeError: 'Chat' object has no attribute 'username'
handlers.py:115 #INFO     [2025-10-03 19:57:01,694] - root - 0| Handler called. ChatAction
mtprotosender.py:319 #INFO     [2025-10-03 19:57:15,758] - telethon.network.mtprotosender - 0| Disconnecting from 149.154.167.51:443/TcpFull...
mtprotosender.py:339 #INFO     [2025-10-03 19:57:15,758] - telethon.network.mtprotosender - 0| Disconnection from 149.154.167.51:443/TcpFull complete!
