mtprotosender.py:228 #INFO     [2025-09-24 16:31:23,620] - telethon.network.mtprotosender - 0| Connecting to 149.154.167.51:443/TcpFull...
mtprotosender.py:279 #INFO     [2025-09-24 16:31:23,995] - telethon.network.mtprotosender - 0| Connection to 149.154.167.51:443/TcpFull complete!
handlers.py:15 #INFO     [2025-09-24 16:31:50,570] - root - 0| Handler called. NewMessage. type = <class 'telethon.tl.patched.Message'>
updates.py:590 #ERROR    [2025-09-24 16:31:51,084] - telethon.client.updates - 0| Unhandled exception on event_new_message
Traceback (most recent call last):
  File "C:\Users\Valentyn\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\updates.py", line 574, in _dispatch_update
    await callback(event)
  File "D:\PythonProjects\tgbot-microservice\app\handlers.py", line 50, in event_new_message
    language_code=sender.language_code
AttributeError: 'User' object has no attribute 'language_code'
handlers.py:15 #INFO     [2025-09-24 16:31:52,443] - root - 0| Handler called. NewMessage. type = <class 'telethon.tl.patched.Message'>
updates.py:590 #ERROR    [2025-09-24 16:31:52,671] - telethon.client.updates - 0| Unhandled exception on event_new_message
Traceback (most recent call last):
  File "C:\Users\Valentyn\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\updates.py", line 574, in _dispatch_update
    await callback(event)
  File "D:\PythonProjects\tgbot-microservice\app\handlers.py", line 50, in event_new_message
    language_code=sender.language_code
AttributeError: 'User' object has no attribute 'language_code'
handlers.py:15 #INFO     [2025-09-24 16:31:57,965] - root - 0| Handler called. NewMessage. type = <class 'telethon.tl.patched.Message'>
updates.py:590 #ERROR    [2025-09-24 16:31:58,208] - telethon.client.updates - 0| Unhandled exception on event_new_message
Traceback (most recent call last):
  File "C:\Users\Valentyn\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\updates.py", line 574, in _dispatch_update
    await callback(event)
  File "D:\PythonProjects\tgbot-microservice\app\handlers.py", line 50, in event_new_message
    language_code=sender.language_code
AttributeError: 'User' object has no attribute 'language_code'
mtprotosender.py:319 #INFO     [2025-09-24 16:32:17,607] - telethon.network.mtprotosender - 0| Disconnecting from 149.154.167.51:443/TcpFull...
mtprotosender.py:339 #INFO     [2025-09-24 16:32:17,607] - telethon.network.mtprotosender - 0| Disconnection from 149.154.167.51:443/TcpFull complete!
base_events.py:1758 #ERROR    [2025-09-24 16:32:17,638] - asyncio - 0| Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000020CA67D9330>
