mtprotosender.py:228 #INFO     [2025-09-24 16:42:19,647] - telethon.network.mtprotosender - 0| Connecting to 149.154.167.51:443/TcpFull...
mtprotosender.py:279 #INFO     [2025-09-24 16:42:19,721] - telethon.network.mtprotosender - 0| Connection to 149.154.167.51:443/TcpFull complete!
updates.py:443 #INFO     [2025-09-24 16:43:08,658] - telethon.client.updates - 0| Got difference for channel 1968379726 updates
handlers.py:15 #INFO     [2025-09-24 16:43:08,659] - root - 0| Handler called. NewMessage. type = <class 'telethon.tl.patched.Message'>
handlers.py:15 #INFO     [2025-09-24 16:43:08,659] - root - 0| Handler called. NewMessage. type = <class 'telethon.tl.patched.Message'>
mtprotosender.py:319 #INFO     [2025-09-24 16:43:18,281] - telethon.network.mtprotosender - 0| Disconnecting from 149.154.167.51:443/TcpFull...
mtprotosender.py:339 #INFO     [2025-09-24 16:43:18,283] - telethon.network.mtprotosender - 0| Disconnection from 149.154.167.51:443/TcpFull complete!
base_events.py:1758 #ERROR    [2025-09-24 16:43:18,341] - asyncio - 0| Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000203235290C0>
base_events.py:1758 #ERROR    [2025-09-24 16:43:18,341] - asyncio - 0| Unclosed connector
connections: ['deque([(<aiohttp.client_proto.ResponseHandler object at 0x0000020323564C40>, 532937.531)])']
connector: <aiohttp.connector.TCPConnector object at 0x0000020323529C60>
base_events.py:1758 #ERROR    [2025-09-24 16:43:18,341] - asyncio - 0| Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x0000020323529EA0>
transport: <_ProactorSocketTransport fd=1008 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "C:\Users\Valentyn\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 690, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Users\Valentyn\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 365, in write
    self._loop_writing(data=bytes(data))
  File "C:\Users\Valentyn\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 401, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
